image: python:3.6

stages:
  - test 
  - deploy

test:
  script:
    - pip install codecov
    - pip install -r requirements.txt
    - ./test.it

deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN mcte-docker.ipjtl.net
  script:
    - docker build -t $CI_REGISTRY_IMAGE:acceptance .
    - docker push $CI_REGISTRY_IMAGE:acceptance


