stages:
  - test
  - deploy

test:
  stage: test
  image: python:3.6

  script:
    - pip install -r requirements.txt
    - py.test --cov=app.py --cov=utils.py

deploy:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t mcte-docker.ipjtl.net/lanlytics-api-server:acc -f dockerfiles/flask .
    - docker push mcte-docker.ipjtl.net/lanlytics-api-server:acc


