language: python
dist: xenial
services: docker
python:
- '3.7'
- '3.6'
- '3.5'
cache: pip
env:
  matrix:
  - secure: cv450iG2h7zxPrRxJlILT9vwZ+TBrVnlzLh7hhBfF2Xa+HNivjH5ZOLtUPxPj4qXQJzrg87cnNvmvTKXsSVmVCv9AgnF+aslxzrL1pxIP3VA5tc/x6Ko23tbCq4OHN3NzZjWxKzek4x6K84Kk/ZgLBQe+TgyAcPdK8S0Yas9vvdouulcK+L3cZAehjD5f+sj3JEJvzKV3hHxCjCelUCOmPbJg4PVkz2HssXICE43iSxvksRkz6WPmFToVqU3G7KiA8l3bG8ZJY3z1afiUgV18amKSYOPO2VX8ESg3U5ZkNVNCv0F5oxEeGB1vsHWoR/dvZyt5EIrce+R9kzxLcDlt9WR19A4dLIpMP6nxnXJI2K8FVlgTOircjpvOFioZrz+riGqExsv0yFssHRm020Tw7mxtJqLyYSn/+uUe9dEz1pKxUlpgDZj0FxiNcHb2i53MZYqx3B3bt2semKAteBMjf6KIkaenqP65DyrKBDNv/HhrJdkUA6QIHnyhbGAdFhxShveSEbm7vr4rmkhmmYUOqRijqrgRO+JBEw2afy1XDRlk7OSTiZL1ruSQg7ZRB+jtbp1MbGYZ4JoyKIGkRBgiK9jvTg3NVD7slueJkbk9bpjP1cMMhnUomhG1GXOcM8SQ0Y7lwfouy4MKF2Xaoq6tVnxV7fmlNAmS2+7AQl0gLg=
  - secure: pvue5kf1J+snaqa9CLne8ZGZREMdnLEQKnLmhTRu+VFfs5JaLC5dKNBjpN4ihPxJ41ucD/mmk1H2Y6Cn4V6P/8TrQMrEufF+MIRgTyjXZEgKE+wkl1qPTpVlhj/uAopQfsN1tWMBVz69CrsJLEvi7tTJVs3b9vteL3NtVHcaF/TpehFpSo86DTSJJ8u1YuFoowNRm5WrMwRtKfXV/W5zd1wjngB15jFQ9bRYDIln52iArjLI3bpjzBBBy1udfawCqECqQvKo8KYAC+wZO3B/obMNLt7ydPA7JFtduYkhk+q3TPbAVrjVA5dPlhz2PLACGoPaje7t2Cy+7DD4I6xWDfhBBTEV6+aSfrXHtQ4jU7d4b2E6ruyRWEVxoTjlhomVJYySvN8Vgr8nVcs7+TdzY9OT6loJDJYR1qVYIBkOE6YYGKY8rt6jlkyuMahEi8ahy07JQWt5nxaQvYA+CMN083igkCkwXsmuzQ5X/pIV5ex/85QfOShr245E6AHI34/khTBOgQtkAq9KW+151am4C3AE2qHTPjAUkYjux9QmonH7L5sOCfHFJY3KsBp1lirwTcPZYUhEtf0BWoq2ZCWQY8zS/sIxHoRRgtITLDKjf06/qbLZFOzaUTRvNiwGrTLIPJnrjyF0Rp59j1YOpCdbXkaCF5lf/v8qe9C9+t/j3Ns=
install: pip install -e .[dev]
script: py.test --cov flexes_build
after_success:
- codecov
deploy:
  provider: script
  script: bash docker_deploy
  on:
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION = '3.7'"
    tags: true
