language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
cache: pip

install: pip install -r requirements.txt

script: py.test --cov=app.py --cov=utils.py --cov=deploy.py

after_success: codecov -u https://cov.lanlytics.com -t da396262-2b5b-413b-9ba7-125adfb99373
