language: python
dist: xenial
services: docker
python:
- '3.7'
- '3.6'
- '3.5'
cache: pip
env:
  global:
  - secure: ujjcIEKIj5aTOBlPGMgwZv5sirGfUAMrpUPRLSbG3pDGNN6yIrQXyw2RYmoIkU95ow4xM4ZXk0pHj/XFfJLFceqJB+4lw7rroPhNQsqgS1YjBec/3FUgpm4R7TxIudsBrCPsLm5v1WFt7Xlcukv51Rdr732Sm8m99yfeXB2anyi5Uqsh6WRd9l/LkHVBTY3opbMEmB55O8GU1tB8sD/x4VX1SZ98+5Ga6o6gXYvsE76v7KoyS9j8djP3nrbmGT/UfheFvbOyrlxrRmwqjGhjp7RnzFvrZ80Atkxo5MPTMwH7C9c29CFnLFsCEr1NkpA3cj9hj4+t7Vzc5LW3Hann8z9qQ40aIGTHyd7jz7fbBnsvhwGnwKvatBl3FhUlGGHCvS4W17Fo6KQwlKAfpHZ9FaROTex4/emrWZ3gsrd3XB+3Q3tGUOVF6Z+IWHeb06DhmcrFa5Q5ouJ4hPCcj3/ryDex2PkVxvx8EdewUddFxVSooXA3OVG1TsVgg1Uec4cTRSyf0Kydx210dKFW9EqLqi/Wn1Y+fjzjeGnbQg+ZxzPnE3+MTrGmlB0QngcLp75n7nFueRFiAU5fnwPmF1aZWlTw9uK9E0+tF2h51SJ6Tx+l+NaX/+HQCgMSocvFopBUn84uQmzKWEYzCd7pBX4YkVDOQR5vpn7wwY6bdo3pZAQ=
  - secure: tUbAfRyNswQDxP5n6JtEd+MkmwV7EO793gGXRKVYstG9V5UjcD+NvONYkCY9IioGFN7ajiQEN4hkVgoXsrghfLNflDq+G6K4OVieylUhNq1WufmgAp40bp1CqJ3D+JqJKrz8HQOGhnG1VPmjZRpJlLMuArvCBb9uQdNbFZyP/s2GqqU+KAG197ZCRzx19lulLAbrS62IQkKrhW+3NZT7J7/mewa1dbdPDp+mC764Vz+53PZW0FDqcPxWrTZYeQYR2bGxEClRiF589pKJGNt1dr1lZLMuJx5LLqF5skfYYpOzk9t9zFmfXasv610NW0nbKLeTAQVgL+jK/MXVLI7FPddNL+OgJip7RQNLkd/aKBVMaSytz0XojYjuLkt3XYwNgJGLCgOWV090dXDVqrSS97kMBFMQwh+9naYSU7PDWYxgoAwI9DwA+2HeLb5cUPGFHjjSmdWctgUWouiHVCbZcgq5stM+V7W6G4jRwLJDNXDzpxPaCo+63x2Mr8M6X3bjPACxkN96R3ckwXLG1BtwCRAchPOVEuWtOL7hxN1060qnaUbxRoomv8O0FCv0A27M0FniAjQe/tNqiVogdYy4mLdLB1W2QIHSHqDpOTSC9f/hREWJqItggcx73ubeZFNmlX318PjaK1HYm6PNnpZSvM9sFnlMba8hwzPIg9CrUY8=
install: pip install -e .[dev]
script: py.test --cov flexes_build
after_success:
- codecov
deploy:
  provider: script
  script: bash docker_deploy
  on:
    branch: master
    condition: "$TRAVIS_PYTHON_VERSION = '3.7'"
    tags: true
