language: python
python:
  - "3.5"
  - "3.4"
  - "2.7"
cache: pip

install:
  - pip install codecov
  - pip install -r requirements.txt

script: ./test.it

after_success:
  - codecov -u https://cov.lanlytics.com -t 4c712a6d-f6be-4053-a8ce-25823936fdd9
