language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
cache: pip

install:
  - pip install codecov
  - pip install -r requirements.txt

script: ./test.it

after_success:
  - bash <(curl -s https://cov.lanlytics.com/bash) -t "zvYVxfDUQ2Swtbv11JFS" -r nisac/lanlytics-api-worker