version: "2"
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    container_name: lanlytics-api-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:8080"
    links:
      - flask:flask
  flask:
    environment:
      - AWS_DEFAULT_REGION=us-gov-west-1
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/flask
    container_name: lanlytics-api-server
    ports:
      - 127.0.0.1:8000:8000
    command: gunicorn app:app -b :8000 -u flask --name lanlytics-api
