version: '3'
services:
  nginx:
    restart: always
    build: 
      context: .
      dockerfile: ./dockerfiles/nginx
    container_name: nginx
    ports:
      - "80:8080"
      - "443:8443"
    links:
      - flask:flask
  flask:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/flask
    container_name: flask
    expose: 
      - "8000"
    command: gunicorn app:app -b :8000 -u flask --name lanlytics-api
