version: "2"
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    container_name: flexes-server-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:8080"
    links:
      - flask:flask
  flask:
    environment:
      - AWS_DEFAULT_REGION=<aws-region-name>
    restart: always
    image: arnoldj/flexes-server
    build:
      context: ../../
      dockerfile: ./Dockerfile
    container_name: flexes-server
    volumes:
      - ./config.json:/home/flask/flexes_build/config.json:ro
    ports:
      - 127.0.0.1:8000:8000
    command: gunicorn flexes_build.server.app:app -b :8000 -u flask --name flexes-server
